### ISSUE TITLE
Source file missing from tree

### ISSUE THREAD

**Issue by bluewhale** [macan/Pomegranate#5]
[root@vs1 Pomegranate]# make
make: **\* No rule to make target `/usr/src/Pomegranate/test/xnet/cr.c', needed by`unit_test'.  Stop.

**Comment by macan** [comment]
Yep, file cr.c is missing in my commits. I will add it to the source tree a few days later, because I am on vocation now. You can walk around it by just removing cr.c in Makefile.inc. And please refer to the fixed wiki page 'Getting Start'.
Thanks!

**Comment by macan** [comment]
It is ok to close this issue.
